[theme]
primaryColor = "#5E6AD2"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F7F8FA"
textColor = "#1A1A1D"
font = "sans serif"

[server]
maxUploadSize = 50
maxMessageSize = 200

[browser]
gatherUsageStats = false
